import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import InstaLogLogo from "../components/InstalogLogo";



const Naviagtion: React.FunctionComponent = () => {
  return (
    <header className="fixed transition ease-in-out duratio-100 top-0 z-30 w-full bg-black-95 backdrop-blur-md block">
      <div className="flex items-center justify-between w-full max-w-screen-lg mx-auto">
        <div className="hidden w-full text-sm font-medium nav-desktop lg:block">
          <div className="flex items-center justify-between w-full max-w-screen-lg py-4 mx-auto">
            <div className="flex items-center justify-start w-1/3">
              <span >
                <a >
                  <InstaLogLogo />
                </a>
              </span>
            </div>
            <div className="flex items-center justify-center flex-grow antialiased">

            </div>
            <div className="flex items-center justify-end w-1/3">
              <ul className="flex items-center">
                <li >
                  <Link href={'/dashboard'}>
                    <a className="px-3 py-2 text-black uppercase rounded-full bg-gray-200 hover:bg-black hover:text-white border-gray-200 hover:border-gray-200 border transition ease-out duration-150">LOGIN</a>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen font-sans">
        <Naviagtion />
      </div>
    </>
  );
};



export default Home;
