import { IncomingMessage, ServerResponse } from "http";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import InstaLogLogo from "../components/InstalogLogo";
import { getServerAuthSession } from "../server/common/get-server-auth-session";



const Naviagtion: React.FunctionComponent = () => {
  return (
    <header className="fixed transition ease-in-out duratio-100 top-0 z-30 w-full bg-black-95 backdrop-blur-md block">
      <div className="flex items-center justify-between w-full max-w-screen-lg mx-auto">
        <div className="w-full text-sm font-medium nav-desktop lg:block">
          <div className="flex items-center justify-between w-full max-w-screen-lg py-4 mx-auto">
            <div className="flex items-center justify-start w-1/3">
              <span >
                <a >
                  <InstaLogLogo />
                </a>
              </span>
            </div>
            <div className="flex items-center justify-center flex-grow antialiased">

            </div>
            <div className="flex items-center justify-end w-1/3">
              <ul className="flex items-center">
                <li >
                  <Link href={'/dashboard'}>
                    <a className="px-3 py-2 text-black uppercase rounded-full bg-gray-200 hover:bg-black hover:text-white border-gray-200 hover:border-gray-200 border transition ease-out duration-150">LOGIN</a>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </header>

  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Instalog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen font-sans">
        <Naviagtion />
        <section className="text-white">
          <div className="max-w-screen-xl px-4 py-32 mx-auto lg:h-screen lg:items-center lg:flex">
            <div className="max-w-3xl mx-auto text-center">
              <h1 className="text-3xl font-extrabold text-transparent sm:text-5xl bg-clip-text bg-gradient-to-r from-indigo-300 via-indigo-500 to-indigo-600">
                Cloud infra for logging
                <span className="sm:block h-[56px] mt-3">
                  <ul className="relative w-full h-full text-center">
                    <li className="animatedListItem">Incidents</li>
                    <li className="animatedListItem">Team Activities</li>
                    <li className="animatedListItem">Actions</li>
                  </ul>
                </span>
              </h1>
              <p className="max-w-xl mx-auto mt-4 sm:leading-relaxed sm:text-xl">
                Instalog is a cloud based logging platform for teams. It helps teams to log their activities and incidents.
              </p>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};


export async function getServerSideProps(context: { req: IncomingMessage & { cookies: Partial<{ [key: string]: string; }>; }; res: ServerResponse; }) {
  const session = await getServerAuthSession(context);
  if (session && session.user != null) {
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false,
      },
    };
  }
  return {
    props: {

    },
  };

}

export default Home;
